version: '2.1'
orbs:
  win: circleci/windows@5.0
jobs:
  build:
    executor:
      name: win/default
    steps:
      - checkout
      - run: Write-Host 'Hello, Windows'
      - run: 
          name: Setup VCPKG
          command: |
            git clone https://github.com/microsoft/vcpkg
            .\vcpkg\bootstrap-vcpkg.bat
          shell: powershell
      - run: 
          name: VCPKG integrate
          command: .\vcpkg\vcpkg integrate install
          shell: powershell      
workflows:
  my-workflow:
    jobs:
      - build
