version: '2.1'
orbs:
  win: circleci/windows@5.0
jobs:
  build:
    machine:
      image: windows-server-2022-gui:2023.09.1
    steps:
      - run: nvm install 16
    
workflows:
  my-workflow:
    jobs:
      - build
